version: "2"
services:
  dnam-mainserver:
    image: dnam_mainserver_image:latest
    restart: unless-stopped
    container_name: dnam-mainserver
    environment:
        - "JAVA_OPTS=-Dmetrics.reporter=influxdb -Ddb.host=dnam_db -Dws.enabled=true"
    networks:
      dnam_network:
    depends_on:
    - dnam_db
    links:
    - dnam_db
    entrypoint: ./wait-for-it.sh
    command: dnam_db:3306 --timeout=20 -- ./entrypoint.sh
  dnam_db:
    image: mariadb:latest
    container_name: dnam_db
    networks:
        dnam_network:
    environment:
      MYSQL_USER: tnmuser
      MYSQL_PASSWORD: d4NaZ9j3k
      MYSQL_DATABASE: tnmdb
      MYSQL_ROOT_PASSWORD: root
  node1:
    image: artifactory.transmode.se/tm3k/trunk-hostenv
    container_name: node1
    environment:
      - DEMO=true
      - NOSIM=1
    privileged: true
    networks:
      dnam_network:
        ipv4_address: 172.35.0.101
  node2:
    image: artifactory.transmode.se/tm3k/trunk-hostenv
    container_name: node2
    environment:
      - DEMO=true
      - NOSIM=1
    privileged: true
    networks:
      dnam_network:
        ipv4_address: 172.35.0.102
  nodes_setup:
    build: nodes_setup
    container_name: nodes_setup
    depends_on:
      - node1
      - node2
    links:
      - node1
      - node2
    networks:
      dnam_network:
#  alarmservice_test:
#    image: se.infinera.metro.service.acceptance.alarm/alarmservice-acceptance-test-all:1.0-SNAPSHOT
#    container_name: alarmservice_test
#    networks:
#      alarmservice_network:
#    depends_on:
#      - alarmservice
#      - nodes_setup
#    links:
#        - alarmservice
#    entrypoint: ./wait-for-it.sh
#    command: alarmservice:8080 --timeout=20 -- ./entrypoint.sh
networks:
  dnam_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.35.0.0/24 # Allows for 255 addresses